### ISSUE TITLE
No longer works on updated site

### ISSUE THREAD

**Issue by staridiot** [d9beuD/monstercat-dl#2]
Hello, Monstercat recently updated their site and removed the ability to download via the `data-play-link` tag. I'm assuming that's how the script worked originally? Either way, only the hash method works now, perhaps you can update the script? This is an incredibly useful tool, especially now that Monstercat's site is a pain to navigate.

**Comment by d9beuD** [comment]
Hello, as Monstercat's pages are built in JavaScript, my script can't just download the page and get the `data-play-link` attribute on the play button. So I use the Monstercat API to find data needed to build the play link, then I use it to download the music file.
I will soon work on an update of my script so it fits the updated Monstercat API.

**Comment by d9beuD** [comment]
Hi @staridiot, this tool is working again, thank you for your patience. Please read the new usage section, there have been some changes.
